# Intellibrand - Data Engineer Test Case

In [1]:
# #############################################################################
# Lucas Lukasavicus Silva
# March 03, 2023
# lukasavicus at gmail dot com
# -----------------------------------------------------------------------------
# Code Test 4 Data Engineer @ Intellibrand
# #############################################################################

Ficamos muito felizes com o seu interesse nesta vaga e esse teste é de grande importância para que possamos avaliar o seu conhecimento técnico, criatividade e organização no desenvolvimento da tarefa. Nosso trabalho diário é desenvolver e implementar soluções de dados que aumentam a performance dos nossos clientes nos principais sites de varejo online. Por isso, criamos este desafio técnico para simular uma atividade que é realizada pelos nossos times especialistas. Nessa tarefa, você deverá encontrar **os 10 produtos com a maior variação de preço, entre o valor encontrado no varejo online (Americanas) e o estipulado pelo fabricante**, e **os 10 produtos que apresentam maior indisponibilidade**. _Nosso cliente deseja observar com essa task se existem produtos que estão sendo vendidos com valores muito distantes do ideal_. Para isso, disponibilizamos dados coletados nos varejos em diferentes datas para que possa desenvolver essa atividade. Alguns pontos importantes sobre a estrutura dos nossos dados:

- "retailerPrice" -- é preço encontrado no varejo;
- "manufacturerPrice" -- é preço indicado pelo fabricante;
- "priceVariation" -- é a variação do preço, pode ser negativa ou positiva.
- “available” – se o produto está disponível para compra

O escopo do teste deve incluir, mas não se restringindo:
- Ingestão dos dados;
- Armazenamento dos arquivos;
- Tratamento dos dados;
- Cálculo das métricas;

Desejáveis:
- Aplicação de PyLint ou similar;
- Aplicação de Clean Code;
- Diagrama da pipeline;
- Readme;
- Coverage e Testes unitários;


Os arquivos para o teste estão em formato .zip no link;

https://drive.google.com/file/d/14nMMC19vpQ8s69TqCkQZh7SxJxlpaOzW/view?usp=sharing

Esperamos que o resultado seja entregue em um repositório GIT.
Boa sorte!

---

In [2]:
import os
from pathlib import Path
import json
import pandas as pd
import numpy as np
from zipfile import ZipFile
import os

In [3]:
READ_FROM_ORIGIN = True

In [4]:
base = os.path.join('.', 'datatest', 'root', 'workspace', 'data-eng-test')
files = [path.name for path in Path(base).rglob('*.json')]

In [5]:
# Check some constraints:
# 1. All files are unique on name;
# 2. We can assess the structure of all data

In [6]:
assert len(files) == np.unique(files).size # 1

### Read Data

In [7]:
if(READ_FROM_ORIGIN):
    all_data = []
    errors = []
    until = 1000000
    with ZipFile('datatest.zip') as myzip:
        zip_info = myzip.infolist()
        for i, zipfile in enumerate(zip_info):
            # print("READING", zipfile.filename)
            if('.json' not in zipfile.filename):
                continue
            until -= 1
            if(until == 0): break
            try:
                with myzip.open(zipfile.filename) as myfile:
                    data = json.load(myfile)
                    all_data.append({
                            'file_properties' :
                            {
                                'title' : zipfile.filename
                            },
                            'content' : data,
                            'sk' : i
                        })
            except Exception as e:
                print(e)
                errors.append({'file' : zipfile.filename, 'error' : e, 'sk' : i})
                raise e
    print("Readed", len(all_data))
    only_data = [d['content'] for d in all_data]

Readed 100970

In [8]:
test_cases = [
    {'table1' : [{'explanation' : "Table 1 - same structure", 'a' : 1, 'b' : 'Hello', 'c' : "2022-12-01T00:00:00.000Z"}]},
    {'table1' : [{'explanation' : "Table 1 - same structure", 'a' : 2, 'b' : 'wORLD', 'c' : "2022-12-02T00:00:00.000Z"}]},
    {'table1' : [{'explanation' : "Table 1 - same structure", 'a' : 3, 'b' : 'h-e-l-l-o', 'c' : "2022-12-03T00:00:00.000Z"}]},
    {'table1' : [{'explanation' : "Table 1 - same structure", 'a' : 4, 'b' : 'world', 'c' : "2022-12-041T00:00:00.000Z"}]},
    {'table1' : [{'explanation' : "Table 1 - minus structure", 'a' : 4, 'b' : 'world'}]},
    {'table1' : [{'explanation' : "Table 1 - minus structure", 'a' : 4, 'c' : "2022-12-041T00:00:00.000Z"}]},
    {'table1' : [{'explanation' : "Table 1 - plus structure", 'a' : 4, 'b' : 'world', 'c' : "2022-12-041T00:00:00.000Z", "d" : -456.90}]},
    {'table1' : [{'explanation' : "Composite Table ", 'a' : 4, 'b' : 'world', 'e' : { 'f1' : 1, 'f2' : 2} }]},
    {'table1' : [{'explanation' : "Table 1 - same structure (test1 again)", 'a' : 1, 'b' : 'Hello', 'c' : "2022-12-01T00:00:00.000Z"}]},
    {'table1' : [{'explanation' : "Multi level structure", 'a' : 4, 'b' : 'world', 'e' : { 'f1' : 1, 'f2' : 2, 'f3' : {'c1': None, 'c2' : None} } }]},

]

In [9]:
def extract_signatures(signatures, key, obj):
    # print('='*30)
    # print('signatures', signatures)
    # print('key', key)
    # print('obj', obj)
    # print('+'*30)
    ks = list(obj.keys())
    if(key is not None):
        # print("\n\nSUPER FLAG", signatures[key] is None, '\n\n')
        # print(" Inside>> ", signatures[key])
        if(signatures[key] is not None):
            for _k in ks:
                if(_k not in signatures[key]):
                    signatures[key].append(_k)
        else:
            # if(isinstance(signatures[key], list) or isinstance(signatures[key], dict)):
            signatures[key] = ks
        # print('sk', signatures)
    for k in ks:
        # print('inner signatures', signatures)
        # print('inner k', k)
        if(isinstance(signatures, list)):
            continue
        
        if(k not in signatures):
            signatures[k] = None

        # passing signatures by ref
        if(isinstance(obj[k], list)):
            for item in obj[k]:
                extract_signatures(signatures, k, item)
        elif(isinstance(obj[k], dict)):
            extract_signatures(signatures, k, obj[k])
        else:
            pass
#             print('not covered yet', type(obj[k]), obj[k], k)

---

### Tests:

In [10]:
s = {}
o = test_cases[7]
extract_signatures(s, None, o)
print('s', [item for item in s.items() if item[1] is not None])

s [('table1', ['explanation', 'a', 'b', 'e']), ('e', ['f1', 'f2'])]

In [11]:
signatures = {}
for i, d in enumerate(test_cases):
    # print("TEST CASE", i, d)
    objj = d.copy()
    extract_signatures(signatures, None, objj)

print('s', [item for item in signatures.items() if item[1] is not None])
# signatures

s [('table1', ['explanation', 'a', 'b', 'c', 'd', 'e']), ('e', ['f1', 'f2', 'f3']), ('f3', ['c1', 'c2'])]

---

### Extract Signatures from Data

#### Análise do Schema dos Dados:

Essa análise tem como propósito verificar o schema dos dados e entender como eles se relacionam. A partir dessa análise esperamos poder extrair os dados de forma performática e armazenar os dados em um esquema mais fácil para futuras análises.

In [12]:
len(only_data)

100970

In [13]:
signatures = {}
for d in only_data[:]:
#     print(d, '\n\n')
    objj = d.copy()
    extract_signatures(signatures, None, objj)

In [14]:
# Assinaturas dos Dados
sgnats = [item for item in signatures.items() if item[1] is not None]
print('s', [item for item in signatures.items() if item[1] is not None])

s [('assortment', ['dateTimeReference', 'idRetailerSKU', 'modifiedDate', 'seller', 'retailerFinalUrl', 'retailerProductCode', 'available', 'unavailable', 'notListed', 'screenshot', 'retailerDescription', 'retailerPrice', 'retailerTitle', 'retailerRatingCount', 'retailerFirstImageType', 'heroImageFlag', 'manufacturerExtraImagesTotal', 'manufacturerImagesTotal', 'retailerExtraImagesTotal', 'retailerImagesTotal', 'retailerDescriptionFoundWords', 'descriptionFlag', 'descriptionPercentage', 'manufacturerDescription', 'manufacturerPrice', 'priceInsideRange', 'priceAboveRange', 'priceBelowRange', 'priceOutOfThePolicy', 'priceVariation', 'useManufacturerPriceVariationRule', 'useProductPriceRangeRule', 'retailerTitleFoundWords', 'titleFlag', 'titlePercentage', 'brandRetailerTitle', 'manufacturerTitle', 'retailerAverageRating', 'retailerReviewCount', 'correctExtraImagesTotal', 'extraImagesPercentage', 'primaryImageFlag', 'retailerFromPrice', 'priceDiscount']), ('images', ['idProductCatalog', 'order', 'name', 'specificImage', 'dateTimeReference', 'idRetailerSKU', 'approved', 'percent', 'path', 'manufacturerOrder', 'manufacturerUrl', 'retailerUrl', 'type', 'comparisonDate', 'idUser', 'referenceName']), ('reviews', ['review', 'userName', 'dateTimeReference', 'index', 'idRetailerSKU', 'reviewDate', 'innerRate']), ('variants', ['idRetailerSKU', 'retailerProductCode', 'variant', 'index', 'dateTimeReference']), ('marketplace', ['idRetailerSKU', 'canBuy', 'seller', 'tax', 'dateTimeReference', 'shipper', 'firstParty', 'index', 'unitPrice', 'variation', 'eta'])]

---

In [15]:
# Principais "tabelas" a serem modeladas
for k, v in sgnats:
    print(k)

assortment
images
reviews
variants
marketplace

In [16]:
# Campos da "tabela" Assortment
sgnats[0]

('assortment',
 ['dateTimeReference',
  'idRetailerSKU',
  'modifiedDate',
  'seller',
  'retailerFinalUrl',
  'retailerProductCode',
  'available',
  'unavailable',
  'notListed',
  'screenshot',
  'retailerDescription',
  'retailerPrice',
  'retailerTitle',
  'retailerRatingCount',
  'retailerFirstImageType',
  'heroImageFlag',
  'manufacturerExtraImagesTotal',
  'manufacturerImagesTotal',
  'retailerExtraImagesTotal',
  'retailerImagesTotal',
  'retailerDescriptionFoundWords',
  'descriptionFlag',
  'descriptionPercentage',
  'manufacturerDescription',
  'manufacturerPrice',
  'priceInsideRange',
  'priceAboveRange',
  'priceBelowRange',
  'priceOutOfThePolicy',
  'priceVariation',
  'useManufacturerPriceVariationRule',
  'useProductPriceRangeRule',
  'retailerTitleFoundWords',
  'titleFlag',
  'titlePercentage',
  'brandRetailerTitle',
  'manufacturerTitle',
  'retailerAverageRating',
  'retailerReviewCount',
  'correctExtraImagesTotal',
  'extraImagesPercentage',
  'primaryImageFlag',
  'retailerFromPrice',
  'priceDiscount'])

#### Sobre o Schema de Dados:

Pudemos observar que 4 principais tabelas podem ser modeladas a partir dos dados que temos a disposição, sendo que a principal delas é a tabela de _Assortment_ que contém os dados coletados do retailer.

---

In [17]:
def flatten_assortment(registry):
    fprops = registry['file_properties']
    content = registry['content']
    assortments = content['assortment']
    flatten_registries = []
    for assortment in assortments:
#         print('assortment', assortment)
#         print('fprops', fprops)
        assrtmnt = {**fprops, **assortment}
        assrtmnt['sk'] = registry['sk']
        flatten_registries.append(assrtmnt)
    return flatten_registries

In [23]:
READ_FROM_ORIGIN = False

In [30]:
if(READ_FROM_ORIGIN):
    # Transform JSON files into a Pandas.DataFrame

    flattened_data = [flatten_assortment(d) for d in all_data]
    flattened_list = [item for sublist in flattened_data for item in sublist]
    df = pd.DataFrame(flattened_list)
    
    df.reset_index(drop=True, inplace=True)
    
    df.to_parquet('Datatest.parquet.gzip', compression='gzip')
else:
    df = pd.read_parquet('Datatest.parquet.gzip')

In [49]:
df.describe()

,idRetailerSKU,sk,retailerPrice,retailerRatingCount,retailerFirstImageType,manufacturerExtraImagesTotal,manufacturerImagesTotal,retailerExtraImagesTotal,retailerImagesTotal,descriptionPercentage,...,retailerAverageRating,retailerReviewCount,correctExtraImagesTotal,extraImagesPercentage,retailerFromPrice,priceDiscount,availability,occurence,unavailability,priceVar
count,1.009700e+05,100970.000000,22114.000000,30589.000000,18023.000000,18096.000000,18096.000000,18096.000000,18096.000000,19066.000000,...,24457.000000,22072.000000,17053.000000,17053.000000,2168.000000,2168.000000,100970.000000,100970.0,100970.000000,22114.000000
mean,1.122299e+06,50485.939972,591.492001,965.156233,0.398657,6.362014,7.362622,4.771883,5.769341,60.199725,...,4.497134,4.836988,3.102856,42.480888,1319.819161,72.304405,0.219016,1.0,0.076290,-34.497819
std,5.857988e+05,29148.099452,2133.545231,4598.041848,0.489636,5.078741,5.076059,6.229312,6.229139,35.735667,...,0.465938,1.834030,3.806713,43.058324,3852.285873,235.027508,0.413581,0.0,0.265463,601.246361
min,2.728400e+04,1.000000,0.990000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,...,1.000000,1.000000,0.000000,0.000000,2.290000,-935.180000,0.000000,1.0,0.000000,-11788.650000
25%,6.032950e+05,25243.250000,12.990000,4.000000,0.000000,3.000000,4.000000,0.000000,1.000000,26.670000,...,4.300000,4.000000,0.000000,0.000000,24.990000,2.000000,0.000000,1.0,0.000000,-2.730000
50%,1.008662e+06,50485.500000,25.990000,23.000000,0.000000,6.000000,7.000000,3.000000,4.000000,61.760000,...,4.600000,6.000000,2.000000,28.570000,149.945000,12.990000,0.000000,1.0,0.000000,1.740000
75%,1.840011e+06,75728.750000,193.662500,200.000000,1.000000,8.000000,9.000000,7.000000,8.000000,100.000000,...,4.800000,6.000000,6.000000,91.670000,1641.910000,58.490000,0.000000,1.0,0.000000,12.560000
max,1.981812e+06,100971.000000,43999.990000,33068.000000,1.000000,37.000000,38.000000,47.000000,48.000000,100.000000,...,5.000000,6.000000,23.000000,100.000000,41999.990000,2000.000000,1.000000,1.0,1.000000,4924.280000

In [31]:
dfp = df[[
    'manufacturerTitle',
    'idRetailerSKU', 'retailerPrice', 'manufacturerPrice', 'useManufacturerPriceVariationRule', 'priceBelowRange',
    'priceVariation', 'priceDiscount', 'available', 'unavailable'
]]

In [32]:
dfp[~dfp['retailerPrice'].isnull()]

,manufacturerTitle,idRetailerSKU,retailerPrice,manufacturerPrice,useManufacturerPriceVariationRule,priceBelowRange,priceVariation,priceDiscount,available,unavailable
17,Absorvente Externo Nortuno SEMPRE LIVRE® ADAPT...,1839998,15.90,17.59,True,False,-9.61,NaN,True,False
20,Protetor Solar Corpo e Rosto SUNDOWN® Praia e ...,1839968,38.99,39.76,True,False,-1.94,NaN,True,False
25,Bebida à Base de Castanha-de-Caju Orgânica Ori...,218550,7.99,6.75,False,False,18.37,NaN,True,False
29,Fralda Huggies Tripla Proteção G - 36 fraldas,553313,44.99,44.99,False,False,0.00,NaN,True,False
38,Fralda Pampers Supersec G - 26 unidades,745209,32.99,1.00,True,False,3199.00,NaN,True,False
...,...,...,...,...,...,...,...,...,...,...
100944,NIVEA Creme Hidratante Lata 56g,487947,12.99,20.50,True,True,-36.63,NaN,True,False
100950,Shampoo Hidratação Glicerinada Dove Baby Frasc...,749363,11.99,1.00,True,False,1099.00,NaN,True,False
100956,Cervejeira Consul Cor Titanium com 82L Display...,498709,2499.99,2499.00,True,False,0.04,-478.08,True,False
100963,Shampoo Johnson`s Baby Regular 400ml,749364,17.99,1.00,True,False,1699.00,NaN,True,False
100968,Bisnaguinha Integral Pullman 280g,336203,7.49,7.51,True,False,-0.27,NaN,True,False

---

In [33]:
# 1. Produtos com maior variação de preço entre o Retailer e o Manufacturer:

# Product DataFrame
pdf = df[["idRetailerSKU", "retailerPrice", "manufacturerPrice"]].groupby(by="idRetailerSKU").mean().reset_index()
pdf['priceVariation'] = pdf['retailerPrice'] - pdf['manufacturerPrice']
pdf['absPriceVariation'] = abs(pdf['priceVariation'])

pdf.sort_values(by=['absPriceVariation', 'priceVariation'], ascending=False).head(10)

,idRetailerSKU,retailerPrice,manufacturerPrice,priceVariation,absPriceVariation
3512,1964334,41931.024483,49999.00,-8067.975517,8067.975517
1318,866361,7947.609048,14732.72,-6785.110952,6785.110952
3123,1907007,4866.262857,0.00,4866.262857,4866.262857
3135,1907784,3729.990000,0.00,3729.990000,3729.990000
2809,1876930,6341.369310,9999.00,-3657.630690,3657.630690
2804,1876924,11399.990000,14999.00,-3599.010000,3599.010000
3138,1917908,5420.679655,8999.00,-3578.320345,3578.320345
2803,1876923,4975.852069,8499.00,-3523.147931,3523.147931
3134,1907680,3499.990000,0.00,3499.990000,3499.990000
901,619475,6920.290000,9999.00,-3078.710000,3078.710000

---

In [50]:
# 2. Produtos com maior indisponibilidade:

df['availability'] = df['available'].astype(int)
df['occurence'] = 1
df['unavailability'] = df['unavailable'].astype(int)

# Unavailability DataFrame
udf = df[['idRetailerSKU', 'availability', 'occurence', 'unavailability']].groupby(by='idRetailerSKU').sum().reset_index()
# df[['idRetailerSKU', 'unavailability']].groupby(by='idRetailerSKU').sum().reset_index().sort_values(by='unavailability', ascending=False).head(20)

udf['unavailability_pctg'] = udf.apply(lambda row : (row['unavailability'] / row['occurence'] * 100) if row['occurence'] != 0 else 0 , axis=1)
udf.sort_values(by=['unavailability_pctg', 'unavailability'], ascending=False).head(10)

,idRetailerSKU,availability,occurence,unavailability,unavailability_pctg
7,28005,0,29,29,100.0
16,28711,0,29,29,100.0
22,28885,0,29,29,100.0
30,29149,0,29,29,100.0
32,29199,0,29,29,100.0
34,29273,0,29,29,100.0
51,39939,0,29,29,100.0
53,40494,0,29,29,100.0
56,40759,0,29,29,100.0
57,40794,0,29,29,100.0

In [61]:
itemsUnavailable = list(udf[udf['unavailability_pctg'] == 100]['idRetailerSKU'])
f = df['idRetailerSKU'].apply(lambda sku: sku in itemsUnavailable)

In [62]:
namedItemsUnavailable = np.unique(df[f]['manufacturerTitle'])
print(namedItemsUnavailable)

['2021 Smart TV LG 43" Full HD 43LM6370 WiFi Bluetooth HDR ThinQAI compatível com Inteligência Artificial'
 '2021 Smart Tv Lg 32" Hd 32Lm627B Wifi Bluetooth Hdr Thinqai Compatível Com Inteligência Artificial'
 '2021 Smart Tv Lg 70" 4K Uhd 70Up7750 Wifi Bluetooth Hdr Inteligência Artificial Thinq Smart Magic Google Alexa'
 '2021 Smart Tv Lg 75" 4K Uhd 75Up8050 Wifi Bluetooth Hdr Inteligência Artificial Thinq Smart Magic Google Alexa'
 '2022 Smart TV LG 77" 4K OLED77C2 Evo 120Hz Mais Brilho G-Sync FreeSync 4x HDMI 2.1 ThinQAI Google Alexa'
 '49" LG Ultra HD 4K TV | 49UJ6525' '49" LG Ultra HD 4K TV | 49UJ6565'
 'A-Oxitive Noite, Cuidado peeling, Avène - 30ml'
 'A-Oxitive Olhos, Cuidado contorno dos olhos suavizante, Avène - 15ml'
 'A-Oxitive Sérum, Sérum protetor antioxidante, Avène - 30ml'
 'Absorvente Always Noites Tranquilas Cobertura Suave com 32 unidades'
 'Absorvente Interno Intimus Mini - 16 unidades'
 'Actine Colors FPS 70 Pele Morena, Darrow - 40g'
 'Actine Proteor Solar FPS 60 Cor Universal, Darrow-40'
 'Actine Protetor Solar FPS 30 Sem Cor, Darrow- 40g'
 'Actine Protetor Solar FPS 60 Sem Cor, Darrow-40g'
 'Actine Água Micelar Dermatológica, peles oleosas, Darrow - 100ml'
 'Android TV LED 50” TCL P615 4K UHD HDR com Wifi e Bluetooth integrados, 3 HDMI, 2 USB, Controle Remoto com Comando por controle de Voz e Google Assistant'
 'Ar Condicionado LG DUAL Inverter VOICE 15.000 Frio 220V - S4-Q15JL31A'
 'Ar Condicionado Sem Vento Samsung WindFree Plus 12.000 Btus Quente e Frio (220V)'
 'Ar Condicionado Split Hi-Wall Samsung WindFree Inverter 22.000 BTU/h Quente/Frio 220v | AR24TSHCBWKNAZ'
 'Ar Condicionado Split Inverter Samsung 18000 BTUs WindFree Plus Quente/Frio AR18TSEABWKNAZ - 220v'
 'Ar Condicionado Split Inverter Samsung 9000 BTUs WindFree Quente/Frio AR09TSHCBWKNAZ - 220v'
 'Ar-condicionado Sem Vento Samsung WindFree Plus - Quente e Frio - 9.000 btus (220V) 2021'
 'BRITANIA - MIXER BRITÂNIA BMX350V 350W'
 'BRITANIA - MIXER BRITÂNIA INOX MAXX BMX355P 350W'
 'Batedeira Planetária Arno Deluxe 600W com Tigela Inox e 8 velocidades Vermelha SX72 220v'
 'Batedeira Planetária Arno Super Chef 750W 5 litros 15 velocidades Vermelha KM02 127v'
 'Bisnaguinha Pullman 280g' 'CHÁ LEÃO PRETO NATURAL - 10 SACHÊS'
 'Cafeteira Filtro Arno Preferita Inox com 750ml de Capacidade e Jarra de Vidro CFPF 127v'
 'Cafeteira Filtro Arno Preferita Inox com 750ml de Capacidade e Jarra de Vidro CFPF 220v'
 'Cafeteira Mallory Star Wars - 16 xícaras'
 'Caixa Acústica Lg Xboom Rn7- Multi Bluetooth, Super Graves, Entrada De Microfone E Guitarra'
 'Calculadora de Mesa MV4121 com Visor 12 Digítos Elgin'
 'Cerveja Amstel Lata 350ml'
 'Churrasqueira elétrica Britânia BCQ01D antiaderente 1500W'
 'Cicalfate Lábios, Bálsamo reparador labial intensivo, Avène - 10ml'
 'Cleanance Gel, Gel de limpeza profunda, Avène - 300g'
 'Compacto Dore Fps 50 Avène - Protetor Solar - Avène, 10g'
 'Cooktop 5 bocas Electrolux a Gás 5 Bocas (KE5GP) - Bivolt'
 'Densiage, condicionador anti envelhecimento capilar, Ducray - 200ml'
 'Densiage, shampoo anti envelhecimento capilar, Ducray - 200ml'
 'Doctar Sensi, Shampoo Anticaspa, Darrow 120ml'
 'FOGÃO BRASTEMP 5 BOCAS DUPLO FORNO COR INOX COM BOTÕES REMOVÍVEIS E EXCLUSIVO ARO PROTETOR 110V'
 'FOGÃO BRASTEMP 5 BOCAS DUPLO FORNO COR INOX COM BOTÕES REMOVÍVEIS E EXCLUSIVO ARO PROTETOR 220V'
 'Ferro a Vapor Elétrico Arno Steamgliss Base Antiaderente e Ponta de Precisão FSGP 127v'
 'Ferro a vapor Arno Smartgliss Inteligente com Desligamento Automático FSC1 127v'
 'Fogão Brastemp 4 Bocas de embutir Preto com mesa de vidro e dupla chama  - BYO4XAE- BIVOLT'
 'Forno De Micro-Ondas 30L Revestimento Easyclean, Tecnologia I Wave E 17 Receitas Pré-Programadas'
 'Forno De Micro-Ondas Grill 30L 127V Com Grill De Quartzo E Revestimento Easyclean™'
 'Forno De Micro-Ondas Grill 30L Com Grill De Quartzo E Revestimento Easy Clean'
 'Forno De Micro-Ondas Solo 30L 220V Com Revestimento Easyclean™ E Tecnologia I Wave'
 'Forno Elétrico Arno Airfry 5 em 1 com 20L de Capacidade Preto FOR2 220v'
 'Forno Elétrico Arno Airfry 5 em 1 com 20L de Capacidade Vermelho FOR3 127v'
 'Forno Elétrico Arno Turbo Quartzo 10L de Capacidade e Temporizador FOR1 127v'
 'Forno de Embutir Elétrico Brastemp 84 Litros Cor Inox Espelhado com Convecção e Timer Touch 220V'
 'Fralda Bigfral Confort GD 16 Unidades'
 'Fralda Bigfral Confort Tamanho G 8 Unidades'
 'Fralda Bigfral Plus Normal Tamanho G 16 Unidades'
 'Fralda Bigfral Plus Normal Tamanho G 8 Unidades'
 'Fralda Bigfral Plus Normal Tamanho M 18 Unidades'
 'Fralda Bigfral Plus Normal Tamanho XG 7 Unidades'
 'Fralda Huggies Supreme Care RN - 34 Fraldas'
 'Fralda Pom Pom Derma Protek Jumbo Gd 24Un'
 'Fralda Pom Pom Derma Protek Jumbo M 28Un'
 'Fralda Pom Pom Derma Protek Jumbo P 30Un'
 'Fralda Pom Pom Derma Protek Jumbo Xg 20Un'
 'Fralda Pom Pom Derma Protek Jumbo Xxg 18Un'
 'Fralda Pom Pom Shortinho Jumbo M 36 Unidades'
 'Frigideira Grill Antiaderente Rochedo Inova 28cm'
 'Frigobar Consul 80 litros com Gaveta Multiuso - CRC08CB 110V'
 'Fritadeira Sem Óleo Air Fryer Mondial Family NAF-03I 4L - Preto e Inox'
 'Fritadeira Sem Óleo Air Fryer Mondial Grand Family Inox Red AF-50-RI 5 Litros – Vermelho/Inox'
 'Fritadeira sem Óleo AirFry Arno Moderna com Cuba Antiaderente Preta PFRY 127v'
 'GOOGLE TV LED 55” TCL P635 4K UHD HDR com Wifi dual band e Bluetooth integrados, Controle Remoto com Comando por controle de Voz, Google Assistant e borda fina'
 'Geladeira 371 Litros DFN41 Frost Free Branca Freezer Electrolux'
 'Geladeira Brastemp Frost Free 540L Cor Inox com Ice Maker Side Inverse BRO80AK 220V'
 'Geladeira Brastemp Frost Free Duplex 375L Cor Branca com Espaço Adapt Painel Eletrônico BRM45HB 220V'
 'Geladeira Brastemp Frost Free Duplex 400L Cor Inox com Painel Eltrônico Freeze Control BRM54HK 110V'
 'Geladeira Brastemp Frost Free Duplex 400L Cor Inox com Painel Eltrônico Freeze Control BRM54HK 220V'
 'Geladeira Brastemp Inverse 3 Frost Free 419 litros cor Preta com Freeze Control Pro 110V'
 'Geladeira Brastemp Inverse 3 Frost Free 419 litros cor Preta com Freeze Control Pro 220V'
 'Geladeira Smart Side By Side 601 Litros Com Moist Balance Crisper™ E Compressor Linear Inverter™ 220V'
 'Geladeira/Refrigerador Frost Free Electrolux 371 litros (DFN41)'
 'Geladeira/Refrigerador Frost Free Electrolux 371 litros (DFN41) 110V'
 'Geladeira/Refrigerador Frost Free Electrolux 371 litros (DFN41) 220V'
 'Geladeira/Refrigerador Frost Free Electrolux Inox 371L (DFX41) 110V'
 'Geladeira/Refrigerador Frost Free Electrolux Inox 371L (DFX41) 220V'
 'Geladeira/Refrigerador Top Freezer 431L Branco TF55 Electrolux'
 'Google TV LED 65” TCL P725 4K UHD HDR DOLBY VISION - ATMOS, HDR10 Wifi , Bluetooth , 3 HDMI, 2\r\nUSB, Comando de voz à distância, Google Assistant e borda ultrafina'
 'Google TV LED 75” TCL P725 4K UHD HDR DOLBY VISION - ATMOS, HDR10 , Wifi , Bluetooth , 3 HDMI, 2\r\nUSB, Comando de voz à distância, Google Assistant e borda ultrafina'
 'Hidratante Desodorante NIVEA Firmador Q10 + Vitamina C Todos os Tipos de Pele 400ml'
 'Hidratante Facial e Corporal TriXera Nutrition, Avène- 200ml'
 'Ketchup Heinz 2kg' 'Klinse, Shampoo Anticaspa, Darrow - 140ml'
 'Lava Louças Electrolux 10 Serviços Branca com Função Higienizar Compras (LL10B) 220V'
 'Lava Louças Electrolux 14 Serviços Branca com Função Higienizar Compras (LL14B) 110V'
 'Lava Louças Electrolux 14 Serviços Branca com Função Higienizar Compras (LL14B) 220V'
 'Lava Louças Electrolux 14 Serviços Inox com Função Higienizar (LL14X) 110V'
 'Lava Louças Electrolux 14 Serviços Inox com Função Higienizar (LL14X) 220V'
 'Lava e Seca Brastemp 10kg/6kg branca Água Quente com Ciclo Tira Manchas Pro e Ciclo 1h Pronto para Vestir 110V'
 'Lava e Seca Brastemp 10kg/6kg branca Água Quente com Ciclo Tira Manchas Pro e Ciclo 1h Pronto para Vestir 220V'
 'Lava e Seca Brastemp 10kg/6kg prata Água Quente com Ciclo Tira Manchas Pro e Ciclo 1h Pronto para Vestir 220V'
 'Lava-Louças Brastemp 10 Serviços Cor Branca com Ciclo Pesado e Delicado BLF10BB 110V'
 'Lava-Louças Brastemp 10 Serviços Cor Inox com Ciclo Pesado e Delicado BLF10BR 110V'
 'Lava-Louças Brastemp 10 Serviços Cor Inox com Ciclo Pesado e Delicado BLF10BR 220V'
 'Lavadora Smart Lg Vc5 11Kg Branca Com Inteligência Artificial Aidd™'
 'Lenços Umedecidos Pampers Aroma de Aloe Vera 192 unidades'
 'Lg Blu-Ray Player' 'Lg Xboom Cj44' 'Lhd625.Abrallk'
 'Liquidificador Arno Power Max 1000W Preto Com 6 Lâminas e Jarra de 3,1L LN55 127v'
 'Liquidificador Arno Power Mix Limpa Fácil Off White com Lâminas Removíveis LQ31 220v'
 'Liquidificador Arno Power Mix Limpa Fácil Vinho com Lâminas Removíveis LQ32 127v'
 'Liquidificador Arno Power Mix Limpa Fácil Vinho com Lâminas Removíveis LQ32 220v'
 'Liquidificador Arno Power Mix Plus Preto com Jarra de 2 litros Cristalina LQ20 220v'
 'Liquidificador Arno Power Mix Plus Vermelho com Jarra de 2 litros Cristalina LQ21 127v'
 'Macarrão Instantâneo Nissin Sabor Galinha Caipira 85G'
 'Maionese Heinz Receitas 405g'
 'Micro-Ondas Consul 20L Cor Inox com Função Descongelar Design Moderno e Espelhado CM020BF 110V'
 'Micro-Ondas Consul 20L Cor Inox com Função Descongelar Design Moderno e Espelhado CM020BF 220V'
 'Micro-ondas Brastemp 20 Litros cor Inox Espelhado com Funções Pré-preparo 110V'
 'Micro-ondas Brastemp 32 Litros cor cinza espelhado com Menu Gourmet - BMS46AR- 127V'
 'Micro-ondas Brastemp 38 Litros cor inox espelhado com Grill - BMJ38AR 220V'
 'Micro-ondas Brastemp De Embutir 40 Litros cor inox com Grill - BMO40AR 220V'
 'Mixer Mondial Versatile 220v - M-12'
 'Mixer Portátil Arno Turbomix Pro 3 em 1 Inox com 400W e Copo Medidor MX31 127v'
 'Mixer Portátil Arno Turbomix Pro 3 em 1 Inox com 400W e Copo Medidor MX31 220v'
 'Mixer Portátil Turbomix Arno Duo 200W com Copo Medidor MX21 127v'
 'Mixer Portátil Turbomix Arno Duo 200W com Copo Medidor MX21 220v'
 "Monitor LG 19,5'' LED HD 20MK400H-B"
 "Monitor LG Pro Gamer Ultrawide™ Full HD 29'' - 29UM69G-B"
 'Monitor UltraWide™ LG 34” 21:9 Full HD IPS HDR10 34WK650-W'
 'Mostarda Heinz Sachê 192x5g'
 'Máquina de Café Espresso Automática Vermelha G1 Lov Basic Tres 220V'
 'Máquina de Lavar 16kg Electrolux Perfect Wash Máquina de Cuidar com Cesto Inox e Jet&Clean (LPE16) 110V'
 'Máquina de Lavar 16kg Electrolux Perfect Wash Máquina de Cuidar com Cesto Inox e Jet&Clean (LPE16) 220V'
 'Máquina de Lavar 16kg Electrolux Turbo Economia, Silenciosa com Jet&Clean e Filtro Fiapos (LAC16) 110V'
 'Máquina de Lavar 16kg Electrolux Turbo Economia, Silenciosa com Jet&Clean e Filtro Fiapos (LAC16) 220V'
 'Máquina de Lavar Consul 16Kg com Ciclo Edredom Dispenser Limpa Fácil Dosagem Fácil CWL16AB 110V'
 'Máquina de Lavar Consul 16Kg com Ciclo Edredom Dispenser Limpa Fácil Dosagem Fácil CWL16AB 220V'
 'NIVEA Creme Facial Antissinais 100g' 'NIVEA Creme Facial Nutritivo 100g'
 'NIVEA Demaquilante Bifásico 125ml'
 'NIVEA Desodorante Antitranspirante Roll On Dry Comfort 50ml'
 'NIVEA Desodorante Antitranspirante Roll On Invisible Black & White Clear 50ml'
 'NIVEA Hidratante Labial Amora Shine 4,8 g'
 'NIVEA Lenços de Limpeza Demaquilantes 3 em 1 Refrescante 25 un.'
 'NIVEA Loção Hidratante Óleos Essenciais Coco & Óleo Monoi 200ml'
 'NIVEA MEN Espuma de barbear Original Protect 200ml'
 'NIVEA MEN Espuma de barbear Sensitive 200ml'
 'NIVEA Men Desodorante Aerosol Dry Fresh 150ml'
 'NIVEA Men Desodorante Antitranspirante Roll On Original Protect 50ml'
 'NIVEA SUN Protetor Solar Protect & Hidrata FPS50 400ml'
 'NIVEA Sabonete em Barra Toque de Baunilha 85g'
 'NIVEA Sabonete em barra Antibacteriano 3 em 1 85g'
 'NIVEA Tônico Adstringente Facial Controle do Brilho 200ml'
 'NIVEA Tônico Hidratante Aqua Rose 200ml'
 'Nescafé Dolce Gusto Arno Genio S Plus Multi Bebidas Preta DGS2 127v'
 'Nutricerat, shampoo para cabelo seco, muito seco e danificado , Ducray- 200ml'
 'Nutriol Hidratante Intensivo Dermatológico, perfume suave, Darrow - 200ml'
 'Nutriol Hidratante Intensivo Dermatológico. sem perfume, Darrow - 200ml'
 'Panela de Pressão Philco PPP04PI Multifuncional 4L'
 'Physiolift Sérum, Sérum preenchedor e reparador, Avène - 30ml'
 'ROKU TV LED 43” TCL RS520 FHD Wifi dual band, 3 HDMI, 1 USB, com controle por aplicativo'
 'Repelente Off Active Loção 100ml' 'SK6FF.ABRALLK'
 'Sabonete Pom Pom Leite e Mel 80g'
 'Sabonete Pom Pom Óleo de Amêndoas 80g'
 'Sanduicheira Arno Inox Compacta com Placas Antiaderentes SACS 127v'
 'Sanduicheira Arno Inox Compacta com Placas Antiaderentes SACS 220v'
 'Sanduicheira Grill Arno Dual Inox Abertura 180 graus com Placa Antiaderente GNOX 127v'
 'Sanduicheira Grill Arno Dual Inox Abertura 180 graus com Placa Antiaderente GNOX 220v'
 'Sensinol, shampoo para couro cabeludo sensível ou sensibilizado, Ducray - 200ml'
 'Smart TV 65" LG NanoCell TV | 65SJ8000'
 'Smart TV LED 32" LG HD HDR Ativo e WebOS 4.0' 'Smart TV LG 55" 55LH5750'
 'Smart Tv Lg 32" Hd Hdr Ativo Inteligência Artificial Thinq Ai Virtual Surround Sound'
 'Soapelle Sabonete Antisséptico Líquido, Darrow- 140ml'
 'TCL QLED TV 50” C725 4K UHD GOOGLE TV, DOLBY VISION, HDR10+, com Wifi dual band e Bluetooth integrados, 3 HDMI, 2 USB, Comando de voz à distância, Google Assistant, DOLBY ATMOS e design sem bordas'
 'TV FULL HD 49" LG 49LH5100' 'TV FULL HD LG 43LH5100'
 'TV LG Triple XD Engine' 'Toalha Umedecida Bigfral 40 Unidades'
 'Toalhas Umedecidas Pom Pom Camomila 50 Unidades'
 'Toalhas Umedecidas Pom Pom Camomila Pom Pom Leve 100 Pague 90'
 'Trio Anacaps Activ+, suplemento vitaminico mineral, Ducray- 90 Cápsulas'
 'Vaporizador de roupas Portátil Arno Steam Power HS81 127v'
 'Vaporizador de roupas Portátil Arno Steam Power HS81 220v'
 'Ventilador de Teto Arno Ultimate Branco com 3 Pás e Controle Remoto VX10 127v'
 'Ventilador de Teto Arno Ultimate Branco com 3 Pás e Controle Remoto VX10 220v'
 'Vodka Skyy Infusions Pinapple750ml' 'Água de Colônia Pom Pom 100ml']

---

In [ ]:
for c in df.columns:
    print(c)
    
# notListed, 
# retailerTitle, retailerRatingCount, manufacturerDescription, title, manufacturerTitle

In [ ]:
# Futuras análises:

# a. notListed x unavailable
# b. notListed x priceVariation (eu acho q coisas notListed o pessoal joga o preço pra 0 ou pra 1, então dá uma variação maior);
# c. Será que algum tipo de produto específico apresenta variação maior? Ou indisponibilidade? Tentar fazer uma análise com palavras (título) x essas duas variáveis;

In [40]:
# Análise adicional:
# 1. notListed == Unavailable

print("Unavailable == NotListed? ", sum(df['unavailable'] == df['notListed']) == df.shape[0])
print("notListed is in Unavailable? ", all(df[df['notListed'] == True]['unavailable']))

# R.: Não. E não acredito que isso seja um erro, mas talvez todos que não estão listado deveriam ser marcados como não disponíveis.

Unavailable == NotListed?  False

In [35]:
# Análise adicional:
# 2. notListed == Unavailable

df["priceVar"] = df["retailerPrice"] - df["manufacturerPrice"]
df[['idRetailerSKU', 'notListed', 'unavailable', 'available', "retailerPrice", "manufacturerPrice", "priceVar"]].sort_values(by=['priceVar'], ascending=False).head(30)

,idRetailerSKU,notListed,unavailable,available,retailerPrice,manufacturerPrice,priceVar
53969,1907007,False,False,True,4924.28,0.0,4924.28
52805,1907007,False,False,True,4924.28,0.0,4924.28
17949,1907007,False,False,True,4924.28,0.0,4924.28
15692,1907007,False,False,True,4924.28,0.0,4924.28
24159,1907007,False,False,True,4924.28,0.0,4924.28
69617,1907007,False,False,True,4924.28,0.0,4924.28
25887,1907007,False,False,True,4822.75,0.0,4822.75
96508,1907007,False,False,True,4822.75,0.0,4822.75
8832,1907007,False,False,True,4822.75,0.0,4822.75
48680,1907007,False,False,True,4822.75,0.0,4822.75
63545,1907007,False,False,True,4822.75,0.0,4822.75
74518,1907007,False,False,True,4822.75,0.0,4822.75
77020,1907007,False,False,True,4822.75,0.0,4822.75
62145,1907007,False,False,True,4822.75,0.0,4822.75
94354,1907784,False,False,True,3729.99,0.0,3729.99
96553,1907784,False,False,True,3729.99,0.0,3729.99
29432,1907784,False,False,True,3729.99,0.0,3729.99
22369,1907680,False,False,True,3549.99,0.0,3549.99
10406,1907680,False,False,True,3449.99,0.0,3449.99
46201,1925529,False,False,True,2845.00,1.0,2844.00
47501,1925529,False,False,True,2845.00,1.0,2844.00
33616,1925529,False,False,True,2845.00,1.0,2844.00
14632,1925529,False,False,True,2845.00,1.0,2844.00
78679,1925529,False,False,True,2845.00,1.0,2844.00
46405,1925529,False,False,True,2845.00,1.0,2844.00
36297,1925529,False,False,True,2845.00,1.0,2844.00
17309,1925529,False,False,True,2699.99,1.0,2698.99
63127,1925529,False,False,True,2699.99,1.0,2698.99
60352,1925529,False,False,True,2699.99,1.0,2698.99
155,1925529,False,False,True,2698.00,1.0,2697.00

In [84]:
shortTitle = df['manufacturerTitle'].apply(lambda title : title.split(' ')[0] if title is not None else '')

In [92]:
productUnavailabilityDf = pd.DataFrame(columns=['shortTitle', 'unavailability'], data=list(zip(shortTitle, df['unavailability'])))
productUnavailabilityDf.groupby('shortTitle').sum().reset_index().sort_values(by=['unavailability'], ascending=False).head(20)

                 shortTitle  unavailability
124                   NIVEA             685
77                Geladeira             498
71                   Fralda             405
70                    Forno             370
78   Geladeira/Refrigerador             275
98                     Lava             273
122                 Máquina             238
106          Liquidificador             236
1                      2021             185
9                    Actine             162
118                   Mixer             156
11                       Ar             143
74               Fritadeira             143
115             Micro-ondas             126
158                   Smart             122
153            Sanduicheira             112
120                 Monitor             112
103                      Lg             110
72               Frigideira             106
160                     TCL             105

In [99]:
productPriceVarDf = pd.DataFrame(columns=['shortTitle', 'priceVar', 'item'], data=list(zip(shortTitle, df['priceVar'], list(range(df.shape[0])))))

In [104]:
#productPriceVarDf.groupby('shortTitle').mean().reset_index().sort_values(by=['priceVar'], ascending=False).head(20)

productPriceVarDf.groupby('shortTitle').agg({'priceVar':'mean', 'item': 'count'}).reset_index().sort_values(by=['priceVar'], ascending=False).head(20)

                 shortTitle     priceVar  item
85                     Home  2357.813529    58
112                 Maquina  1844.982000    29
100                Lavadora  1442.297692    57
78   Geladeira/Refrigerador   999.418571   366
116              Microondas   682.400000    56
67                    Fogão   586.388571   395
158                   Smart   474.002291   301
68                     Fone   431.040345    29
5                        AR   360.554483    29
122                 Máquina   240.990802   799
62                    FOGÃO   148.708841   144
98                     Lava   132.945556   282
107                   Loção    92.770000    29
17                 BRITANIA    89.083846   199
108               Luminária    84.090000    45
74               Fritadeira    78.330793   370
150                Sabonete    75.767844  1106
114   Micro-OndasElectrolux    61.080213    58
13                Aspirador    53.904650   200
143                Refletor    45.160455    70